name: 'Nix CI'

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: [osmosis-amd, osmosis-nvidia]

    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: osmosis
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build
        run: |
          nix-build -A packages.x86_64-linux.${{ matrix.package }}

      - if: ${{ github.action_repository == 'ryanccn/osmosis' }}
        name: Push cache to Cachix
        run: |
          # shellcheck disable=SC2046
          nix-store -qR --include-outputs $(nix-store -qd $(nix-build -A packages.x86_64-linux.${{ matrix.package }})) \
            | grep -v '\.drv$' \
            | cachix push osmosis
